
  CREATE TABLE "MS_03_2021_PRODUCTOS"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(6,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(2000 BYTE), 
	"PRECIO" NUMBER(6,0) NOT NULL ENABLE, 
	"STOCK" NUMBER(4,0) NOT NULL ENABLE, 
	"ESTADO" CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY ;

CREATE SEQUENCE SEQ_PRODUCTO;

INSERT INTO PRODUCTO(ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK)
VALUES (SEQ_PRODUCTO.NEXTVAL,'Mouse Cybertel','Mouse inálambrico',30.00,1);

INSERT INTO PRODUCTO(ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK)
VALUES (SEQ_PRODUCTO.NEXTVAL,'Galaxy S9','Galaxy S9 Edge',3000.00,1);

COMMIT;

SELECT ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,ESTADO FROM PRODUCTO;